package com.puroblast.weatherappcompose.utils


const val BASE_URL = "https://api.openweathermap.org/"
const val CITY = "Saint Petersburg"
const val TOKEN = "d9e6fe2ca9bd114df14262b014663852"
const val TAG = "MSGAPP"
const val UNITS = "metric"
const val EMPTY_STRING = ""
const val PRESSURE_METRIC = " hPa"
const val HUMIDITY_METRIC = " %"
const val WIND_METRIC = " m/s"
const val WIND = "Wind"
const val PRESSURE = "Pressure"
const val HUMIDITY = "Humidity"
const val CELSIUS = " \u2103"
const val DEGREE = " \u00B0"
const val VISIBILITY = "Visibility"
const val FEELS_LIKE = "Feels like"
const val CLOUDINESS = "Cloudiness"
const val SUNRISE = "Sunrise time"
const val SUNSET = "Sunset time"
const val MAX_TEMP = "Maximum temperature"
const val MIN_TEMP = "Minimum temperature"
const val NEW_LINE = "\n"